<?php return array(
    'root' => array(
        'name' => 'codeigniter4/appstarter',
        'pretty_version' => 'v4.5.1',
        'version' => '4.5.1.0',
        'reference' => NULL,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'codeigniter4/appstarter' => array(
            'pretty_version' => 'v4.5.1',
            'version' => '4.5.1.0',
            'reference' => NULL,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeigniter4/framework' => array(
            'pretty_version' => 'v4.5.1',
            'version' => '4.5.1.0',
            'reference' => '9b2cd730db29d14ac6e760fb15c4bcac15184ec4',
            'type' => 'project',
            'install_path' => __DIR__ . '/../codeigniter4/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => 'af459883f4018d0f8a0c69c7a209daef3bf973ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'fe5ea303b0887d5caefd3d431c3e61ad47037001',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
